version: '3.8'

networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  elasticsearch-data:
  prometheus-data:
  kafka-data:
  zookeeper-data:
  postgres-data:

x-common-variables: &common-variables
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  ELASTICSEARCH_HOSTS: elasticsearch:9200
  PROMETHEUS_URL: http://prometheus:9090
  POSTGRES_HOST: postgres
  POSTGRES_DB: monitoring
  POSTGRES_USER: monitoring_user
  POSTGRES_PASSWORD: monitoring_pass
  ALERT_TOPIC: alert
  ALERT_CONTEXT_TOPIC: alert-context